title: Sysmon Configuration Modification
id: 1f2b5353-573f-4880-8e33-7d04dcf97744
authors:
  - frack113
history:
  - '20211109: creation of the file'
source: |
  * sysmon
  EventID: 4 or 16
  Channel: Microsoft-Windows-Sysmon/Operational (%SystemRoot%\System32\Winevt\Logs\Microsoft-Windows-Sysmon%4Operational.evtx)
audit: |
  * sysmon
  Sysmon must be installed on configured.
  The basic configuration of sysmon configuration can be found on :
      - https://github.com/SwiftOnSecurity/sysmon-config
      - https://github.com/Neo23x0/sysmon-config
      - https://github.com/olafhartong/sysmon-modular
description: Contribute to the updating of information
code: Contribute to the updating of information
example: Contribute to the updating of information
